// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXrJ3ADwuJLoX8Q21CpBza-kikwH8pzM',
    appId: '1:748028926687:android:5046e1f4ba15e23244276a',
    messagingSenderId: '748028926687',
    projectId: 'flutterprojects-c0ec9',
    storageBucket: 'flutterprojects-c0ec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPtWVx86c5fHIRNw-x-dvmYrFWv9CHpOA',
    appId: '1:748028926687:ios:bcac1994b9bc34b944276a',
    messagingSenderId: '748028926687',
    projectId: 'flutterprojects-c0ec9',
    storageBucket: 'flutterprojects-c0ec9.firebasestorage.app',
    iosBundleId: 'com.example.smartPace',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqIRyqjHHte7ETeawm7mZ3xHae_rKP_vY',
    appId: '1:748028926687:web:06a113389a0cebf544276a',
    messagingSenderId: '748028926687',
    projectId: 'flutterprojects-c0ec9',
    authDomain: 'flutterprojects-c0ec9.firebaseapp.com',
    storageBucket: 'flutterprojects-c0ec9.firebasestorage.app',
    measurementId: 'G-CYNEGB2052',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPtWVx86c5fHIRNw-x-dvmYrFWv9CHpOA',
    appId: '1:748028926687:ios:bcac1994b9bc34b944276a',
    messagingSenderId: '748028926687',
    projectId: 'flutterprojects-c0ec9',
    storageBucket: 'flutterprojects-c0ec9.firebasestorage.app',
    iosBundleId: 'com.example.smartPace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqIRyqjHHte7ETeawm7mZ3xHae_rKP_vY',
    appId: '1:748028926687:web:77b027baed05ba1844276a',
    messagingSenderId: '748028926687',
    projectId: 'flutterprojects-c0ec9',
    authDomain: 'flutterprojects-c0ec9.firebaseapp.com',
    storageBucket: 'flutterprojects-c0ec9.firebasestorage.app',
    measurementId: 'G-BNLJ9N4Y6F',
  );

}